name: Send a slack notification when a contributor comments on issue

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  contributor_issue_comment:
    name: Contributor issue comment

    if: >-
      ${{
        !github.event.issue.pull_request
      }}

    runs-on: ubuntu-latest
    steps:
      - name: Escape title double quotes
        id: escape_title
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: echo "ISSUE_TITLE=${ISSUE_TITLE//\"/\\\"}" >> "$GITHUB_OUTPUT"

      - name: Send message to Slack channel
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "*[${{ github.event.repository.name }}] New comment on issue: <${{ github.event.issue.html_url }}#issuecomment-${{ github.event.comment.id }}|${{ steps.escape_title.outputs.ISSUE_TITLE }} by ${{ github.event.comment.user.login }}>*"
