name: Send a slack notification when a contributor comments on issue

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
        description: Webhook URL for the Slack support-dev channel where notifications should be sent.
      SLACK_COMMUNITY_NOTIFICATIONS_WEBHOOK_URL:
        required: true
        description: Webhook URL for the Slack support-dev-notifications channel where notifications should be sent.


jobs:
  contributor_issue_comment:
    name: Contributor issue comment

    if: >-
      ${{
        !github.event.issue.pull_request
      }}

    runs-on: ubuntu-latest
    steps:
      - name: Generate App Token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout called repository
        uses: actions/checkout@v4
        with:
          repository: testiamshobh/.github
          ref: main
          token: ${{ steps.generate-token.outputs.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependancies
        run: npm install

      - name: Run check script
        id: check
        uses: actions/github-script@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COMMUNITY_NOTIFICATIONS_WEBHOOK_URL: ${{ secrets.SLACK_COMMUNITY_NOTIFICATIONS_WEBHOOK_URL }}
          script: |
              const script = require('./scripts/notify_team_new_comment.js');
              return await script({github, context, core});

      - name: Send message to Slack channel
        if: steps.check.outputs.isMaintainer == 'false'
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook-type: incoming-webhook
          webhook: ${{ secrets.steps.check.outputs.webhook_url }}
          payload: |
            text: ${{ secrets.steps.check.outputs.text }}
